data:
  char_bag: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789~!@#$%^&*(),.<>/?'\"{}[]\\|-_=+;: `\n"

train:
  batch_size: 128
  dense_hidden_size: 512
  epochs: 20
  lstm_hidden_size: 1000

eval:
  checkpoint_frequency: 1
  chunk_size_guesser: 1000