data:
    char_bag: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789~!@#$%^&*(),.<>/?'\"{}[]\\|-_=+;: `\n"
    max_length: 12
    train_test_percentage: 80

train:
    batch_size: 256
    iterations: 100000
    conv1_1dim: 64
    conv1_2dim: 128
    conv1_3dim: 256
    output_size: 1
    learning_rate: 0.0002
    ema_decay: 0.999
    checkpoint_frequency: 10000

