data:
    max_length: 12
    char_bag: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789~!@#$%^&*(),.<>/?'\"{}[]\\|-_=+;: `\n"

train:
    batch_size: 1024
    input_dim: 12
    output_dim: 32
    num_layers: 3
    num_hidden: 128
    activation: "Tanh"
    dropout_prob: 0.5
    dropout_active: False
    lr_rate: 0.01
    epochs: 100
    loss_fn: "SoftBoundary"
    warm_up_epochs: 10
    weight_decay: 1e-2

hyperparams:
    Radius: 1
    nu: 0.01

test:
    batch_size: 500000