data:
    char_bag: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789~!@#$%^&*(),.<>/?'\"{}[]\\|-_=+;: `\n"
    max_length: 12
    train_test_percentage: 80

test:
    runs: 200
    batch_size: 500000

